add solution for avatar component
js-tasks-ru/htmlcss-20240913_sania-kond pull request #10
Opened 2024-10-13 10:32 UTC by Apollosania

2024-10-13 10:32 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-14 04:21 UTC, GSemikozov approved these changes

2024-10-14 04:21 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-10-14 04:21 UTC, GSemikozov requested changes
конфликт

2024-10-14 19:30 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-14 19:32 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-14 19:38 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-14 19:39 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-18 08:20 UTC, GSemikozov requested changes
конфликт

2024-10-18 12:36 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-18 16:24 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-18 16:25 UTC, GSemikozov approved these changes

2024-10-18 16:25 UTC, merged