add solution for histogram component
js-tasks-ru/htmlcss-20240913_sania-kond pull request #6
Opened 2024-10-09 13:16 UTC by Apollosania

2024-10-09 13:16 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-11 10:33 UTC, GSemikozov requested changes

2024-10-11 10:33 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <a class="text text_m text_color_primary text_decoration_none" href="#">View all</a>
я бы не советовал создавать тыщу атомарных классов для описания текста и его вариаций стилизации, лучше самое общее - держать в компоненте текст, а частности - на уровне элементов блоков. Но это просто коммент, не обязательно менять здесь

2024-10-11 10:33 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <a class="text text_m text_color_primary text_decoration_none" href="#">View all</a>
вот как раз и частный случай - сверху нет паддинга в 3px

2024-10-11 10:33 UTC, GSemikozov commented on components/grid/grid.css
> +.grid {
это слишком абстрактное название для компонента, обычно под этим подразумевают универсальную сетку

2024-10-11 10:33 UTC, GSemikozov commented on components/grid/grid.css
> +    grid-template-columns: repeat(12, 1fr);
здесь точно должно быть 12 колонок?

2024-10-11 10:33 UTC, GSemikozov commented on components/card/card.css
> +    aspect-ratio: 1;
какую проблему решаем?

2024-10-12 13:39 UTC, Apollosania commented on 04-lection2/01-histogram/index.html
> +                <a class="text text_m text_color_primary text_decoration_none" href="#">View all</a>
Да, понял, хорошо. На лекциях вроде говорилась, что плохая практика менять стилизацию самого блока из элемента. Только то, что является контекстом, я поэтому так сделал. Тут наверное вообще правильнее будет из ссылки сделать отдельный компонент? А не модифицировать компонент текста?

2024-10-12 13:40 UTC, Apollosania commented on components/grid/grid.css
> +.grid {
да, я думал тут нужно сделать компонент универсальный, для создания сеток. Сделаю тогда частный случай для карточек.

2024-10-12 13:41 UTC, Apollosania commented on components/card/card.css
> +    aspect-ratio: 1;
тут я почему то подумал, что карточка квадратная и важно выдерживать пропорцию, решил задать ей пропорциональные размеры. Но сейчас понял, что это не так, сейчас поправлю, сделаю по-другому

2024-10-12 13:42 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-12 13:56 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-12 14:47 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-14 04:06 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <a class="text text_m text_color_primary text_decoration_none" href="#">View all</a>
не совсем. Менять стили элемента из ЧУЖОГО блока - это плохо. А миксовать - класс блока + класс элемента родительского блока - так можно. Здесь по идее достаточно было бы `class="text text_m histogram__link"`

2024-10-14 04:08 UTC, GSemikozov approved these changes

2024-10-14 04:08 UTC, merged